apiVersion: v1
kind: Service
metadata:
  name: ${{ values.application_name }}
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: ${{ values.application_name }}
    app.kubernetes.io/part-of: ${{ values.application_name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: actuator
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: ${{ values.application_name }}
    app.kubernetes.io/part-of: ${{ values.application_name }}
