apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.deployment_namespace }}
images:
- name: ${{ values.image_name }}
  newName: 958719611210.dkr.ecr.us-west-1.amazonaws.com/${{ values.image_name }}
  newTag: ${{ values.image_tag }}
resources:
- ../../bases
