apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.deployment_namespace }}
resources:
  - ../../../bases
patchesStrategicMerge:
  - ${{ values.application_name }}/${{ values.application_name }}.ing-patch.yaml
