apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.deployment_namespace }}
images:
- name: ${{ values.image_name }}
  newName: 969716159286.dkr.ecr.us-east-1.amazonaws.com/${{ values.image_name }}
resources:
- ../../bases
components:
- git@github.com:thousandeyes/gitops-dr-components.git/environments/prod/us-east-1/k8s2/scale-zero?ref=master
