apiVersion: v1
kind: Pod
metadata:
  labels:
    label: kustomize-builder
spec:
  containers:
    - name: kustomize-build
      {%- if values.github_organization == "te-ee-sandbox" %}
        {%- set registry = "te-engg-dev" %}
      {%- else %}
        {%- set registry = "te-releng-ci" %}
      {%- endif %}
      image: gcr.io/${{ registry }}/jenkins-agents/kustomize-agent:4.0.5-v0.0.5
      command:
        - cat
      tty: true
