apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: asg-patch.deploy.yaml
  target:
    kind: Deployment

resources:
- ${{ values.application_name }}.deploy.yaml
- ${{ values.application_name }}.svc.yaml
- ${{ values.application_name }}-canary.svc.yaml
- ${{ values.application_name }}.ro.yaml
