apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ${{ values.application_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{ values.application_name }}
  strategy:
    canary:
      stableService: ${{ values.application_name }}
      canaryService: ${{ values.application_name }}-canary
      trafficRouting:
        nginx:
          stableIngress: ${{ values.application_name }}
          additionalIngressAnnotations:
            canary-by-cookie: ThousandEyesCanary
      steps:
        - setWeight: 20
        - pause:
            duration: 10m
        - setWeight: 40
        - pause:
            duration: 5m
        - setWeight: 60
        - pause:
            duration: 5m
