apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.deployment_namespace }}

patches:
  - path: asg-patch.deploy.yaml
    target:
      kind: Deployment

resources:
  - ${{ values.application_name }}.deploy.yaml
  - ${{ values.application_name }}.svc.yaml
  - ${{ values.application_name }}.deploy.ro.yaml
  - ${{ values.application_name }}.svc-canary.yaml
  - ${{ values.application_name }}.ing.yaml
