apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.project_id | dump }}
  {%- if values.project_description %}
  description: ${{ values.project_description | dump }}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{ values.github_organization }}/${{ values.project_id }}
    github.com/team-slug: thousandeyes/${{ values.owner }}
    backstage.io/techdocs-ref: dir:.
    cicd.thousandeyes.com/release-info: "true"
  tags:
    - recommended
    - java
    - spring-boot
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner | dump }}
