apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.deployment_namespace }}
images:
- name: ${{ values.image_name }}
  newName: 565095755193.dkr.ecr.eu-central-1.amazonaws.com/${{ values.image_name }}
  newTag: ${{ values.image_tag }}
resources:
- ../../bases
